#Persistencia
javax.persistence.jdbc.url=jdbc:jtds:sqlserver://localhost:1433/FINN_admifarm
javax.persistence.jdbc.user=sa
javax.persistence.jdbc.password=AQsw142536
javax.persistence.jdbc.driver=net.sourceforge.jtds.jdbc.Driver
javax.persistence.jdbc.dataSource.schema=dbo
javax.persistence.jdbc.dataSource.catalog=FINN_admifarm
hibernate.show_sql=false
hibernate.format_sql=false
hibernate.ddl_auto=false
hibernate.dialect=org.hibernate.dialect.SQLServerDialect

#Nivel de Log
logLevel=info